// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../index.js";

/**
 * @example
 *     {
 *         type: "type",
 *         args: {
 *             "key": "value"
 *         }
 *     }
 */
export interface CreateBridgeCommandRequest {
    type: string;
    args: OpikApi.JsonNode;
    timeoutSeconds?: number;
}
