// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "project_id",
 *         runnerName: "runner_name"
 *     }
 */
export interface DaemonPairRegisterRequest {
    projectId: string;
    runnerName: string;
}
