// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "project_id",
 *         role: "role"
 *     }
 */
export interface GetPakeMessagesRequest {
    projectId: string;
    afterStep?: number;
    role: string;
}
