// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../index.js";

/**
 * @example
 *     {
 *         projectId: "project_id",
 *         role: "daemon"
 *     }
 */
export interface GetPakeMessagesRequest {
    projectId: string;
    afterStep?: number;
    role: OpikApi.GetPakeMessagesRequestRole;
}
