// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../index.js";

/**
 * @example
 *     {
 *         projectId: "project_id",
 *         role: "daemon",
 *         payload: "payload"
 *     }
 */
export interface PakeMessageRequest {
    projectId: string;
    role: OpikApi.PakeMessageRequestRole;
    step?: number;
    payload: string;
}
