// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "project_id",
 *         role: "role",
 *         payload: "payload"
 *     }
 */
export interface PakeMessageRequest {
    projectId: string;
    role: string;
    step?: number;
    payload: string;
}
