// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface BridgeCommand {
    commandId?: string;
    runnerId?: string;
    type?: string;
    status?: OpikApi.BridgeCommandStatus;
    args?: OpikApi.JsonNode;
    result?: OpikApi.JsonNode;
    error?: OpikApi.BridgeCommandError;
    timeoutSeconds?: number;
    submittedAt?: Date;
    pickedUpAt?: Date;
    completedAt?: Date;
    durationMs?: number;
}
