// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface BridgeCommandItem {
    commandId?: string;
    type?: string;
    args?: OpikApi.JsonNode;
    timeoutSeconds?: number;
    submittedAt?: Date;
}
