// This file was auto-generated by Fern from our API Definition.

export const DatasetPublicType = {
    Dataset: "dataset",
    TestSuite: "test_suite",
} as const;
export type DatasetPublicType = (typeof DatasetPublicType)[keyof typeof DatasetPublicType];
