// This file was auto-generated by Fern from our API Definition.

export const ExperimentPublicEvaluationMethod = {
    Dataset: "dataset",
    TestSuite: "test_suite",
} as const;
export type ExperimentPublicEvaluationMethod =
    (typeof ExperimentPublicEvaluationMethod)[keyof typeof ExperimentPublicEvaluationMethod];
