// This file was auto-generated by Fern from our API Definition.

export const PakeMessageResponseRole = {
    Daemon: "daemon",
    Browser: "browser",
} as const;
export type PakeMessageResponseRole = (typeof PakeMessageResponseRole)[keyof typeof PakeMessageResponseRole];
