// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface RunnerChecklist {
    command?: string;
    fileTree?: string;
    instrumentation?: OpikApi.Instrumentation;
    instrumentationMatches?: string[];
    childStatus?: string;
    lastCrash?: OpikApi.LastCrash;
}
