// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const BridgeNextRequest: core.serialization.Schema<
    serializers.BridgeNextRequest.Raw,
    OpikApi.BridgeNextRequest
> = core.serialization.object({
    maxCommands: core.serialization.property("max_commands", core.serialization.number().optional()),
});

export declare namespace BridgeNextRequest {
    export interface Raw {
        max_commands?: number | null;
    }
}
