// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { JsonNode } from "../../../../types/JsonNode.js";

export const CreateBridgeCommandRequest: core.serialization.Schema<
    serializers.CreateBridgeCommandRequest.Raw,
    OpikApi.CreateBridgeCommandRequest
> = core.serialization.object({
    type: core.serialization.string(),
    args: JsonNode,
    timeoutSeconds: core.serialization.property("timeout_seconds", core.serialization.number().optional()),
});

export declare namespace CreateBridgeCommandRequest {
    export interface Raw {
        type: string;
        args: JsonNode.Raw;
        timeout_seconds?: number | null;
    }
}
