// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const PairCompleteRequest: core.serialization.Schema<
    serializers.PairCompleteRequest.Raw,
    OpikApi.PairCompleteRequest
> = core.serialization.object({
    projectId: core.serialization.property("project_id", core.serialization.string()),
});

export declare namespace PairCompleteRequest {
    export interface Raw {
        project_id: string;
    }
}
