// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { PakeMessageRequestRole } from "../../types/PakeMessageRequestRole.js";

export const PakeMessageRequest: core.serialization.Schema<
    serializers.PakeMessageRequest.Raw,
    Omit<OpikApi.PakeMessageRequest, "projectId">
> = core.serialization.object({
    role: PakeMessageRequestRole,
    step: core.serialization.number().optional(),
    payload: core.serialization.string(),
});

export declare namespace PakeMessageRequest {
    export interface Raw {
        role: PakeMessageRequestRole.Raw;
        step?: number | null;
        payload: string;
    }
}
