# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .instrumentation import Instrumentation
from .last_crash import LastCrash


class RunnerChecklist(UniversalBaseModel):
    command: typing.Optional[str] = None
    file_tree: typing.Optional[str] = None
    instrumentation: typing.Optional[Instrumentation] = None
    instrumentation_matches: typing.Optional[typing.List[str]] = None
    child_status: typing.Optional[str] = None
    last_crash: typing.Optional[LastCrash] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
