// This file was auto-generated by Fern from our API Definition.

export const GetPakeMessagesRequestRole = {
    Daemon: "daemon",
    Browser: "browser",
} as const;
export type GetPakeMessagesRequestRole = (typeof GetPakeMessagesRequestRole)[keyof typeof GetPakeMessagesRequestRole];
