// This file was auto-generated by Fern from our API Definition.

export const PakeMessageRequestRole = {
    Daemon: "daemon",
    Browser: "browser",
} as const;
export type PakeMessageRequestRole = (typeof PakeMessageRequestRole)[keyof typeof PakeMessageRequestRole];
