// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { PakeMessageResponse } from "../../../types/PakeMessageResponse.js";

export const Response: core.serialization.Schema<
    serializers.runners.getPakeMessages.Response.Raw,
    OpikApi.PakeMessageResponse[]
> = core.serialization.list(PakeMessageResponse);

export declare namespace Response {
    export type Raw = PakeMessageResponse.Raw[];
}
