// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BridgeCommandError: core.serialization.ObjectSchema<
    serializers.BridgeCommandError.Raw,
    OpikApi.BridgeCommandError
> = core.serialization.object({
    code: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace BridgeCommandError {
    export interface Raw {
        code?: string | null;
        message?: string | null;
    }
}
