// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BridgeCommandItem } from "./BridgeCommandItem.js";

export const BridgeNextResponse: core.serialization.ObjectSchema<
    serializers.BridgeNextResponse.Raw,
    OpikApi.BridgeNextResponse
> = core.serialization.object({
    commands: core.serialization.list(BridgeCommandItem).optional(),
});

export declare namespace BridgeNextResponse {
    export interface Raw {
        commands?: BridgeCommandItem.Raw[] | null;
    }
}
