// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CreateBridgeCommandResponse: core.serialization.ObjectSchema<
    serializers.CreateBridgeCommandResponse.Raw,
    OpikApi.CreateBridgeCommandResponse
> = core.serialization.object({
    commandId: core.serialization.property("command_id", core.serialization.string().optional()),
});

export declare namespace CreateBridgeCommandResponse {
    export interface Raw {
        command_id?: string | null;
    }
}
