// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DaemonPairRegisterResponse: core.serialization.ObjectSchema<
    serializers.DaemonPairRegisterResponse.Raw,
    OpikApi.DaemonPairRegisterResponse
> = core.serialization.object({
    runnerId: core.serialization.property("runner_id", core.serialization.string().optional()),
    expiresInSeconds: core.serialization.property("expires_in_seconds", core.serialization.number().optional()),
});

export declare namespace DaemonPairRegisterResponse {
    export interface Raw {
        runner_id?: string | null;
        expires_in_seconds?: number | null;
    }
}
