// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Instrumentation: core.serialization.ObjectSchema<
    serializers.Instrumentation.Raw,
    OpikApi.Instrumentation
> = core.serialization.object({
    tracing: core.serialization.boolean().optional(),
    entrypoint: core.serialization.boolean().optional(),
    configuration: core.serialization.boolean().optional(),
});

export declare namespace Instrumentation {
    export interface Raw {
        tracing?: boolean | null;
        entrypoint?: boolean | null;
        configuration?: boolean | null;
    }
}
