// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LastCrash: core.serialization.ObjectSchema<serializers.LastCrash.Raw, OpikApi.LastCrash> =
    core.serialization.object({
        exitCode: core.serialization.property("exit_code", core.serialization.number().optional()),
        stderrTail: core.serialization.property("stderr_tail", core.serialization.string().optional()),
    });

export declare namespace LastCrash {
    export interface Raw {
        exit_code?: number | null;
        stderr_tail?: string | null;
    }
}
