// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PakeMessageResponseRole } from "./PakeMessageResponseRole.js";

export const PakeMessageResponse: core.serialization.ObjectSchema<
    serializers.PakeMessageResponse.Raw,
    OpikApi.PakeMessageResponse
> = core.serialization.object({
    role: PakeMessageResponseRole.optional(),
    step: core.serialization.number().optional(),
    payload: core.serialization.string().optional(),
});

export declare namespace PakeMessageResponse {
    export interface Raw {
        role?: PakeMessageResponseRole.Raw | null;
        step?: number | null;
        payload?: string | null;
    }
}
