// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Instrumentation } from "./Instrumentation.js";
import { LastCrash } from "./LastCrash.js";

export const RunnerChecklist: core.serialization.ObjectSchema<
    serializers.RunnerChecklist.Raw,
    OpikApi.RunnerChecklist
> = core.serialization.object({
    command: core.serialization.string().optional(),
    fileTree: core.serialization.property("file_tree", core.serialization.string().optional()),
    instrumentation: Instrumentation.optional(),
    instrumentationMatches: core.serialization.property(
        "instrumentation_matches",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    childStatus: core.serialization.property("child_status", core.serialization.string().optional()),
    lastCrash: core.serialization.property("last_crash", LastCrash.optional()),
});

export declare namespace RunnerChecklist {
    export interface Raw {
        command?: string | null;
        file_tree?: string | null;
        instrumentation?: Instrumentation.Raw | null;
        instrumentation_matches?: string[] | null;
        child_status?: string | null;
        last_crash?: LastCrash.Raw | null;
    }
}
