// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetPakeMessagesRequestRole: core.serialization.Schema<
    serializers.GetPakeMessagesRequestRole.Raw,
    OpikApi.GetPakeMessagesRequestRole
> = core.serialization.enum_(["daemon", "browser"]);

export declare namespace GetPakeMessagesRequestRole {
    export type Raw = "daemon" | "browser";
}
